import turtle
turtle.color('yellow')
turtle.bgcolor('red')
turtle.speed(5)
turtle.penup()
turtle.goto(-300,150)
turtle.pendown()
turtle.begin_fill()
for i in range(5):
    turtle.left(144)
    turtle.back(100)
turtle.end_fill()    
turtle.penup()
turtle.goto(-140,250)
turtle.pendown()
turtle.begin_fill()
for i in range (5):
    turtle.left(144)
    turtle.back(50)
turtle.end_fill()     
turtle.penup()
turtle.goto(-100,180)
turtle.pendown()
turtle.begin_fill()
for i in range(5):
    turtle.left(144)
    turtle.back(50)   
turtle.end_fill() 
turtle.penup()
turtle.goto(-125,100)
turtle.pendown()
turtle.begin_fill()
for i in range(5):
    turtle.left(144)
    turtle.back(50)   
turtle.end_fill() 
turtle.penup()
turtle.goto(-180,30)
turtle.pendown()
turtle.begin_fill()
for i in range (5):
    turtle.left(144)
    turtle.back(50) 
turtle.end_fill()
turtle.penup()
